global:
  resolve_timeout: 5m
  smtp_smarthost: 
  smtp_from: 
  smtp_auth_username: 
  smtp_auth_password: 

route:
  receiver: slack
  group_by: [alertname]

receivers:
    - name: mail
      email_configs:
      - to: 
      
    - name: slack
      slack_configs:
      - api_url: 
        channel: 