

pipeline { 
    agent any  

	environment {
	}
    stages {
	    stage ('Deploy monitoring stack') {
	        steps {
	        	sh "docker stack rm monitoring"
                sh "docker stack deploy -c monitoring.yml monitoring"
	    	}
	    }
	}
    post {
        success {
         	slackSend(color: "#BDFFC3", message: "Monitoring stack deployed: ${env.JOB_NAME}.${env.BUILD_NUMBER} '${GIT_COMMENT}'\n ${GIT_COMMITERS} ${env.BUILD_URL}")
        }
        failure {
       		echo "Job failed"
       		slackSend(color: "#FF9FA1", message: "Monitoring stack deploy failed: ${env.JOB_NAME}.${env.BUILD_NUMBER} '${GIT_COMMENT}'\n ${GIT_COMMITERS} ${env.BUILD_URL}")
        }
    }
}
