version: '3.1'

services:

  master:
    image: madena/jenkins
    ports:
      - 9999:8080
      - 50000:50000
    volumes: 
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - jenkins-user
      - jenkins-pass

  slave:
    image: madena/jenkins-slave:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
        
secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true
    
    
volumes:
  jenkins-data: