{
 "title": "SpringBoot MicroService APIs",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Service",
    "query": "label_values(jvm_classes_loaded, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(jvm_classes_loaded{job=~\"[[job]]\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{job=~\"[[job]]\"}"
    }
   ]
  },
  {
   "title": "Server Requests Per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri != \"/actuator/prometheus\", job=~\"[[job]]\", instance=~\"[[instance]]\"}[1m])",
     "legendFormat": "{{method}}-{{status}}-{{uri}}"
    }
   ]
  },
  {
   "title": "Active Http Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{uri != \"/actuator/prometheus\", job=~\"[[job]]\", instance=~\"[[instance]]\"}"
    }
   ]
  },
  {
   "title": "Active Database Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dataSource_connections_active{job=~\"[[job]]\", instance=~\"[[instance]]\"}"
    }
   ]
  }
 ]
}