version: "3.7"

services:

  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    #cmd: "mssql > create databse sa;"
    volumes:
      - sqlserver:/var/opt/mssql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Standard
      - SA_PASSWORD=

volumes:
  sqlserver:
